# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 5.5
  - 5.4

sudo: false

install:
  - echo "DROP DATABASE IF EXISTS test" | mysql -h127.0.0.1 -uroot;
  - echo "CREATE DATABASE test" | mysql -h127.0.0.1 -uroot;
  - cat var/db/schema/images.sql | mysql -h127.0.0.1 -uroot test;

script:
  - phpunit --bootstrap=tests/bootstrap.php tests/
  #vendor/bin/phpunit --bootstrap=tests/bootstrap.php tests/
