# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 5.6
  - 5.5
  - 5.4

sudo: false

script:
  - phpunit --bootstrap=tests/bootstrap.php tests/
  #vendor/bin/phpunit --bootstrap=tests/bootstrap.php tests/
